### ISSUE TITLE
custom screeps server push?

### ISSUE THREAD

**Issue by JestDotty** [screeps/grunt-screeps#14]

**Comment by cbgbt** [comment]
There are a few [pull](https://github.com/screeps/grunt-screeps/pull/10) [requests](https://github.com/screeps/grunt-screeps/pull/11) which add this functionality, but it seems there is a reluctance to merge due to missing built-in password auth and code upload support in the screeps server.

There's a separate [fork](https://github.com/cbgbt/grunt-screeps-customserver) also available [on npm](https://www.npmjs.com/package/grunt-screeps-customserver) which may be helpful, but it depends on [screepsmod-auth](https://github.com/ScreepsMods/screepsmod-auth)

**Comment by MilesBHuff** [comment]
Read the documentation:  http://docs.screeps.com/contributed/advanced_grunt.html

**Comment by JestDotty** [comment]
forgot I had this open. Built my own in node recently after this.
